##A#Create Article
POST localhost:8080/article/mod
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY4Nzg4MzQsImlkIjoyMiwicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTcwNjk2NTIzNCwiaXNzIjoiS3VuVXpUZXN0In0.Apyonz5s6oUEFBD2wgNYiILREncnz30gUYgn30a5rAIWEgoZFhWQ2VB1DUtjHtXHt3059mCZZn0g5P0Zp3nStQ

{
  "title": "salom",
  "description": "salomlar",
  "content": "salomjon",
  "imagesId": "123",
  "regionId": 1,
  "categoryId": 1
}