
###Created Admin
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "husen@mail.ru",
  "password": "1999"
}

//{
//  "email": "moderator@mail.com",
//  "password": "$Maderotor$"
//}

####Registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Husen",
  "surname": "Husenjon",
  "email": "husenteshayev8@gmail.com",
  "password": "Husenjon123@"
}

###Verification By email
GET localhost:8080/auth/verification/email/1
###Verification By phone number
POST localhost:8080/auth/verification/phone/
Content-Type: application/json

{
  "code": "37348",
  "phoneNumber": "998939559030"
}

