
###Created Admin
POST localhost:8080/auth/login
Accept-Language: UZ
Content-Type: application/json
//#admin1
#
#{
#  "email": "Adminceek123@gmail.com",
#  "password": "58e7dbf8dc93865be732403e79fbd4eb"
#}

//#admin2
//{
//  "email": "husen@mail.ru",
//  "password": "1999"
//}

//#moderator
//{
//  "email": "moderator@mail.com",
//  "password": "$1Maderotor1$"
//}

//#publisher
{
  "email": "publisher@mail.com",
  "password": "@1Publisher1@"
}
//#user
//{
//  "email": "ccccccccc@mail.com",
//  "password": "@1Usercccccccc1@"
//}
####
//#user
//{
//     "email": "userjon@mail.com",
//     "password": "@1Userjon1@"
//}
//#user2
//{
//     "email": "aaaaaa@mail.com",
//     "password": "@1Useraaaaaa1@"
//}
####




####Registration
POST localhost:8080/auth/registration
Accept-Language: RU
Content-Type: application/json

{
  "phoneNumber": "998991339906",
  "name": "Registratsiya2",
  "surname": "Registratsiyabek",
  "email": "husenhusenov8@gmail.com",
  "password": "Registratsiyabek1123@"
}

###Verification By email
GET localhost:8080/auth/verification/email/1
Accept-Language: UZ
###Verification By phone number
POST localhost:8080/auth/verification/phone
Accept-Language: EN
Content-Type: application/json

{
  "code": "51188",
  "phoneNumber": "998991339906"
}

