###Get email history by email
GET localhost:8080/emailHistory/husenteshayev8@gmail.com
###Get email history by date
GET localhost:8080/emailHistory/date?date=2024-02-14
###Get email history pagination
GET localhost:8080/emailHistory/adm/pagination?page=1
#admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjEyNzMsImVtYWlsIjoiaHVzZW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3NjczLCJpc3MiOiJLdW5VelRlc3QifQ.C_FcVg-aFkBq-D23OHoeGjBm5c788bck9YKKKOISvCQjyBad3uxkpFQHEPscIpTVHMbJmpTLZd7kyUGP_jkrYg
