###Create ArticleLike
POST localhost:8080/articleLike/any/95363822-48d3-4374-b24e-7ca7fc2a1c82
Content-Type: application/json
#admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgxNTY2MjIsImVtYWlsIjoiaHVzZW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MjQzMDIyLCJpc3MiOiJLdW5VelRlc3QifQ.EmyC8Af2XWn6f0HqZDNwDdJTMHhDF8zBDsihuKFUjtYOE9ix3gkXowL5enILhRvXtM3P199tvBJm8jHXZiNogw
##moderator
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgxNTY5MjAsImVtYWlsIjoibW9kZXJhdG9yQG1haWwuY29tIiwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwiZXhwIjoxNzA4MjQzMzIwLCJpc3MiOiJLdW5VelRlc3QifQ.rep6TC3nL1BKSsWgkQTdvBTQ_oJwhbTRo_dBqxDemxdHH5ESiaMa6rCeNtahrhj0F8g5zAzIAesi2-VWP86xaw
##publisher
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4NDAxMzksImVtYWlsIjoicHVsaXNoZXJAbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9QVUJMSVNIRVIiLCJleHAiOjE3MDc5MjY1MzksImlzcyI6Ikt1blV6VGVzdCJ9.E1i6fmijw5jPPzQiE7tuwTo8yb5vOuW9mrzoc_jsBquxP02xLeGq1zk0ZepL56_d7gq83puhbLKVyGWLrjL9lQ

{
  "status": "LIKE"
}
###Create CommentLike
POST localhost:8080/commentLike/2
Content-Type: application/json
#admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjEyNzMsImVtYWlsIjoiaHVzZW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3NjczLCJpc3MiOiJLdW5VelRlc3QifQ.C_FcVg-aFkBq-D23OHoeGjBm5c788bck9YKKKOISvCQjyBad3uxkpFQHEPscIpTVHMbJmpTLZd7kyUGP_jkrYg
##moderator
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4OTE4MjUsImVtYWlsIjoibW9kZXJhdG9yQG1haWwuY29tIiwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwiZXhwIjoxNzA3OTc4MjI1LCJpc3MiOiJLdW5VelRlc3QifQ.nt2ZKlUa500gVfGvMDGGdmciNT1Br0LmP1rgNqOCFJ8LR0mUmRsGgT6y8T7XcytPrbTJ12-gPRenn9tvcIMWEg
##publisher
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4NDAxMzksImVtYWlsIjoicHVsaXNoZXJAbWFpbC5jb20iLCJyb2xlIjoiUk9MRV9QVUJMSVNIRVIiLCJleHAiOjE3MDc5MjY1MzksImlzcyI6Ikt1blV6VGVzdCJ9.E1i6fmijw5jPPzQiE7tuwTo8yb5vOuW9mrzoc_jsBquxP02xLeGq1zk0ZepL56_d7gq83puhbLKVyGWLrjL9lQ

{
  "status": "LIKE"
}