###Created Profile
POST localhost:8080/profile/adm
Content-Type: application/json
#admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjEyNzMsImVtYWlsIjoiaHVzZW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3NjczLCJpc3MiOiJLdW5VelRlc3QifQ.C_FcVg-aFkBq-D23OHoeGjBm5c788bck9YKKKOISvCQjyBad3uxkpFQHEPscIpTVHMbJmpTLZd7kyUGP_jkrYg

{
  "name": "cccccccc",
  "surname": "cccccccc",
  "email": "ccccccccc@mail.com",
  "password": "@1Usercccccccc1@",
  "role": "Role_USER"
}

//{
//  "name": "modera",
//  "surname": "tor",
//  "email": "moderator@mail.com",
//  "password": "$Maderotor$",
//  "role": "MODERATOR"
//}

###Update profile
PUT localhost:8080/profile/adm/6
Content-Type: application/json
#admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjEyNzMsImVtYWlsIjoiaHVzZW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3NjczLCJpc3MiOiJLdW5VelRlc3QifQ.C_FcVg-aFkBq-D23OHoeGjBm5c788bck9YKKKOISvCQjyBad3uxkpFQHEPscIpTVHMbJmpTLZd7kyUGP_jkrYg

{
  "name": "bbbbb",
  "surname": "bbbbbbbbb",
  "email": "bbbbbbbb@gmail.com",
  "status": "ACTIVE",
  "role": "ROLE_MODERATOR"
}

###Update profile detail
PUT localhost:8080/profile/any/updateDetail
Content-Type: application/json
#admin
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjEyNzMsImVtYWlsIjoiaHVzZW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3NjczLCJpc3MiOiJLdW5VelRlc3QifQ.C_FcVg-aFkBq-D23OHoeGjBm5c788bck9YKKKOISvCQjyBad3uxkpFQHEPscIpTVHMbJmpTLZd7kyUGP_jkrYg
#moderator
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjI5NjEsImVtYWlsIjoiYWFhYWFhQG1haWwuY29tIiwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwiZXhwIjoxNzA3OTA5MzYxLCJpc3MiOiJLdW5VelRlc3QifQ.VI-aEnIPg7fsUsNl5FhrYLopgqcXvaECLuCHTzTPkvixIv8giv32EpNTkHr_Hd6rBnhgOckdOSnVKnkrwjwLmQ

{
  "name": "hasan",
  "surname": "teshayev"
}

###Delete profile
DELETE localhost:8080/profile/adm/7
#admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjEyNzMsImVtYWlsIjoiaHVzZW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3NjczLCJpc3MiOiJLdW5VelRlc3QifQ.C_FcVg-aFkBq-D23OHoeGjBm5c788bck9YKKKOISvCQjyBad3uxkpFQHEPscIpTVHMbJmpTLZd7kyUGP_jkrYg

###Profile filter
POST localhost:8080/profile/filter
Content-Type: application/json

{
  "name": "husen",
  "surname": "teshayev"
}

