###Created Profile
POST localhost:8080/profile/adm
Accept-Language: RU
Content-Type: application/json
#admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgxNTY2MjIsImVtYWlsIjoiaHVzZW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MjQzMDIyLCJpc3MiOiJLdW5VelRlc3QifQ.EmyC8Af2XWn6f0HqZDNwDdJTMHhDF8zBDsihuKFUjtYOE9ix3gkXowL5enILhRvXtM3P199tvBJm8jHXZiNogw

{
  "name": "pulisher",
  "surname": "publisherov",
  "email": "publisher@mail.com",
  "password": "@1Publisher1@",
  "role": "ROLE_PUBLISHER"
}

//{
//  "name": "cccccccc",
//  "surname": "cccccccc",
//  "email": "ccccccccc@mail.com",
//  "password": "@1Usercccccccc1@",
//  "role": "ROLE_USER"
//}

//{
//  "name": "modera",
//  "surname": "tor",
//  "email": "moderator@mail.com",
//  "password": "$1Maderotor1$",
//  "role": "ROLE_MODERATOR"
//}

###Update profile
PUT localhost:8080/profile/adm/6
Accept-Language: RU
Content-Type: application/json
#admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjEyNzMsImVtYWlsIjoiaHVzZW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3NjczLCJpc3MiOiJLdW5VelRlc3QifQ.C_FcVg-aFkBq-D23OHoeGjBm5c788bck9YKKKOISvCQjyBad3uxkpFQHEPscIpTVHMbJmpTLZd7kyUGP_jkrYg

{
  "name": "bbbbb",
  "surname": "bbbbbbbbb",
  "email": "bbbbbbbb@gmail.com",
  "status": "ACTIVE",
  "role": "ROLE_MODERATOR"
}

###Update profile detail
PUT localhost:8080/profile/any/updateDetail
Accept-Language: RU
Content-Type: application/json
#admin
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjEyNzMsImVtYWlsIjoiaHVzZW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3NjczLCJpc3MiOiJLdW5VelRlc3QifQ.C_FcVg-aFkBq-D23OHoeGjBm5c788bck9YKKKOISvCQjyBad3uxkpFQHEPscIpTVHMbJmpTLZd7kyUGP_jkrYg
#moderator
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjI5NjEsImVtYWlsIjoiYWFhYWFhQG1haWwuY29tIiwicm9sZSI6IlJPTEVfTU9ERVJBVE9SIiwiZXhwIjoxNzA3OTA5MzYxLCJpc3MiOiJLdW5VelRlc3QifQ.VI-aEnIPg7fsUsNl5FhrYLopgqcXvaECLuCHTzTPkvixIv8giv32EpNTkHr_Hd6rBnhgOckdOSnVKnkrwjwLmQ

{
  "name": "hasan",
  "surname": "teshayev"
}

###Delete profile
DELETE localhost:8080/profile/adm/7
Accept-Language: RU
#admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4MjEyNzMsImVtYWlsIjoiaHVzZW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTA3NjczLCJpc3MiOiJLdW5VelRlc3QifQ.C_FcVg-aFkBq-D23OHoeGjBm5c788bck9YKKKOISvCQjyBad3uxkpFQHEPscIpTVHMbJmpTLZd7kyUGP_jkrYg

###Profile filter
POST localhost:8080/profile/filter
Content-Type: application/json

{
  "name": "husen",
  "surname": "teshayev"
}

