###Created Profile
POST localhost:8080/profile/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcyMDk5NTAsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDcyOTYzNTAsImlzcyI6Ikt1blV6VGVzdCJ9.KSgDH7r8t_T4qSAW0m4nia3Rof8rViBnue4hm8ll_egkJi8rzKH0_aCNJBpt-Q0ZYAw1VmM1I_aMjePuxK16eQ

{
  "name": "publer",
  "surname": "pub",
  "email": "pulisher@mail.com",
  "password": "@Publisher777",
  "role": "PUBLISHER"
}

//{
//  "name": "modera",
//  "surname": "tor",
//  "email": "moderator@mail.com",
//  "password": "$Maderotor$",
//  "role": "MODERATOR"
//}

###Update profile
PUT localhost:8080/profile/adm/50
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0Mzk3NjMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MjYxNjMsImlzcyI6Ikt1blV6VGVzdCJ9.Es5Cl7Btme8r1fdBhYTbstW-1GVraShPfl_-xOzcE4KDyagfLSF6rJlHssNnyoGQaf__CbHQ_m36At4CM1vyoA

{
  "name": "hasan",
  "surname": "teshayev",
  "email": "hasan@gmail.com",
  "status": "ACTIVE",
  "role": "MODERATOR"
}

###Update profile detail
PUT localhost:8080/profile/adm/updateDetail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0Mzk3NjMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MjYxNjMsImlzcyI6Ikt1blV6VGVzdCJ9.Es5Cl7Btme8r1fdBhYTbstW-1GVraShPfl_-xOzcE4KDyagfLSF6rJlHssNnyoGQaf__CbHQ_m36At4CM1vyoA

{
  "name": "husen",
  "surname": "teshayev"
}

###Delete profile
DELETE localhost:8080/profile/adm/50
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0Mzk3NjMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MjYxNjMsImlzcyI6Ikt1blV6VGVzdCJ9.Es5Cl7Btme8r1fdBhYTbstW-1GVraShPfl_-xOzcE4KDyagfLSF6rJlHssNnyoGQaf__CbHQ_m36At4CM1vyoA

###Profile filter
POST localhost:8080/profile/filter
Content-Type: application/json

{
  "name": "husen",
  "surname": "teshayev"
}

