###Get sms history by phone number
GET localhost:8080/sms_history/1
###Get sms history by date
GET localhost:8080/sms_history/date?date=2024-01-31
###Get sms history pagination
GET localhost:8080/smsHistory/adm/pagination?page=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY2ODgzODMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY3NzQ3ODMsImlzcyI6Ikt1blV6VGVzdCJ9.BXyxdRoby7PvnT92eFzdlmZ5frhpO44ftc7rrO02F7bOQqH1oNrp30iM5cyDCWlhuei8fEgm_SLI6fEjnr0Pjw
